-- MySQL Script generated by MySQL Workbench
-- Tue Dec  4 10:24:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Logy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Logy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Logy` DEFAULT CHARACTER SET utf8 ;
USE `Logy` ;

-- -----------------------------------------------------
-- Table `Logy`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logy`.`USER` ;

CREATE TABLE IF NOT EXISTS `Logy`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`idUSER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logy`.`SCHEDULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logy`.`SCHEDULE` ;

CREATE TABLE IF NOT EXISTS `Logy`.`SCHEDULE` (
  `idSCHEDULE` INT NOT NULL AUTO_INCREMENT,
  `startHour` TIME NOT NULL,
  `endHour` TIME NOT NULL,
  `day` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSCHEDULE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logy`.`LOGBOOK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logy`.`LOGBOOK` ;

CREATE TABLE IF NOT EXISTS `Logy`.`LOGBOOK` (
  `idLOGBOOK` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `LOGBOOKcol` VARCHAR(100) NULL,
  `LOGBOOKcol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idLOGBOOK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logy`.`PROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logy`.`PROJECT` ;

CREATE TABLE IF NOT EXISTS `Logy`.`PROJECT` (
  `idPROJECT` INT NOT NULL AUTO_INCREMENT,
  `USER_idUSER` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `SCHEDULE_idSCHEDULE` INT NULL,
  `LOGBOOK_idLOGBOOK` INT NOT NULL,
  PRIMARY KEY (`idPROJECT`),
  INDEX `fk_PROJECT_USER1_idx` (`USER_idUSER` ASC),
  INDEX `fk_PROJECT_SCHEDULE1_idx` (`SCHEDULE_idSCHEDULE` ASC),
  INDEX `fk_PROJECT_LOGBOOK1_idx` (`LOGBOOK_idLOGBOOK` ASC),
  CONSTRAINT `fk_PROJECT_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `Logy`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROJECT_SCHEDULE1`
    FOREIGN KEY (`SCHEDULE_idSCHEDULE`)
    REFERENCES `Logy`.`SCHEDULE` (`idSCHEDULE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROJECT_LOGBOOK1`
    FOREIGN KEY (`LOGBOOK_idLOGBOOK`)
    REFERENCES `Logy`.`LOGBOOK` (`idLOGBOOK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logy`.`ACTIVITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logy`.`ACTIVITY` ;

CREATE TABLE IF NOT EXISTS `Logy`.`ACTIVITY` (
  `idACTIVITY` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `location` VARCHAR(200) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `LOGBOOK_idLOGBOOK` INT NOT NULL,
  PRIMARY KEY (`idACTIVITY`),
  INDEX `fk_ACTIVITY_LOGBOOK1_idx` (`LOGBOOK_idLOGBOOK` ASC),
  CONSTRAINT `fk_ACTIVITY_LOGBOOK1`
    FOREIGN KEY (`LOGBOOK_idLOGBOOK`)
    REFERENCES `Logy`.`LOGBOOK` (`idLOGBOOK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
