site_name: LogyDoc
theme:
  name: 'material'

nav:
  - Accueil: index.md
  - Documentation : documentation.md
  - Conception : document_conception.md
  - Résalisation : document_realisation.md

use_directory_urls : false
